"""add_all_sic_tables

Revision ID: 18b111fd811f
Revises: acb6d03f7b72
Create Date: 2026-08-16 07:11:52.699117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18b111fd811f'
down_revision: Union[str, Sequence[str], None] = 'acb6d03f7b72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('despachos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('responsable_id', sa.Uuid(), nullable=False),
    sa.Column('fecha_despacho', sa.Date(), nullable=False),
    sa.Column('numero_lote_despacho', sa.String(length=50), nullable=True),
    sa.Column('estado_producto', sa.String(length=50), nullable=True),
    sa.Column('propietario_pulpa', sa.String(length=200), nullable=True),
    sa.Column('origen_carga', sa.String(length=200), nullable=True),
    sa.Column('destino_carga', sa.String(length=200), nullable=True),
    sa.Column('detalle_transporte', sa.Text(), nullable=True),
    sa.Column('codigo_ncoi', sa.String(length=100), nullable=True),
    sa.Column('precio_bs_kg', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_kg', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('total_bs', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('estado_pulpa', sa.String(length=20), nullable=True),
    sa.Column('entregado_por_nombre', sa.String(length=200), nullable=True),
    sa.Column('entregado_por_ci', sa.String(length=20), nullable=True),
    sa.Column('entregado_por_cargo', sa.String(length=100), nullable=True),
    sa.Column('conductor_nombre', sa.String(length=200), nullable=True),
    sa.Column('conductor_ci', sa.String(length=20), nullable=True),
    sa.Column('conductor_cargo', sa.String(length=100), nullable=True),
    sa.Column('autorizado_por_nombre', sa.String(length=200), nullable=True),
    sa.Column('autorizado_por_ci', sa.String(length=20), nullable=True),
    sa.Column('autorizado_por_cargo', sa.String(length=100), nullable=True),
    sa.Column('entregado_destino_nombre', sa.String(length=200), nullable=True),
    sa.Column('entregado_destino_ci', sa.String(length=20), nullable=True),
    sa.Column('entregado_destino_cargo', sa.String(length=100), nullable=True),
    sa.Column('recibido_por_nombre', sa.String(length=200), nullable=True),
    sa.Column('recibido_por_ci', sa.String(length=20), nullable=True),
    sa.Column('recibido_por_cargo', sa.String(length=100), nullable=True),
    sa.Column('fecha_recibido', sa.Date(), nullable=True),
    sa.Column('cantidad_recibida_kg', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.ForeignKeyConstraint(['responsable_id'], ['usuarios_sistema.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lotes_materia_prima',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('numero_lote', sa.String(length=50), nullable=False),
    sa.Column('comunidad_id', sa.Integer(), nullable=False),
    sa.Column('responsable_id', sa.Uuid(), nullable=False),
    sa.Column('es_organico', sa.Boolean(), nullable=False),
    sa.Column('fruto', sa.String(length=50), nullable=False),
    sa.Column('fecha_apertura', sa.DateTime(), nullable=False),
    sa.Column('fecha_cierre', sa.DateTime(), nullable=True),
    sa.Column('total_kg', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('total_bs', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.Column('motivo_rechazo', sa.Text(), nullable=True),
    sa.Column('rechazado_en', sa.DateTime(), nullable=True),
    sa.Column('vobo_control', sa.Boolean(), nullable=False),
    sa.Column('vobo_planta', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['comunidad_id'], ['comunidades.id_comunidad'], ),
    sa.ForeignKeyConstraint(['responsable_id'], ['usuarios_sistema.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_lote')
    )
    op.create_table('sesiones_choque_termico',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('responsable_id', sa.Uuid(), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=True),
    sa.Column('hora_final', sa.Time(), nullable=True),
    sa.Column('es_organico', sa.Boolean(), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('firma_responsable_planilla', sa.Boolean(), nullable=False),
    sa.Column('vobo_planta', sa.Boolean(), nullable=False),
    sa.Column('vobo_control_calidad', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['responsable_id'], ['usuarios_sistema.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entregas_recolector',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('numero_entrega', sa.String(length=50), nullable=True),
    sa.Column('recolector_id', sa.Integer(), nullable=False),
    sa.Column('lote_materia_prima_id', sa.Integer(), nullable=True),
    sa.Column('fecha_recoleccion', sa.Date(), nullable=True),
    sa.Column('fecha_entrega', sa.Date(), nullable=True),
    sa.Column('tipo_envase', sa.String(length=50), nullable=True),
    sa.Column('peso_kg', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('hora_cosecha', sa.Time(), nullable=True),
    sa.Column('hora_recepcion', sa.Time(), nullable=True),
    sa.Column('medio_transporte', sa.String(length=50), nullable=True),
    sa.Column('estado_recepcion', sa.String(length=20), nullable=True),
    sa.Column('firma_recolector', sa.Boolean(), nullable=False),
    sa.Column('firma_responsable_acopio', sa.Boolean(), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['lote_materia_prima_id'], ['lotes_materia_prima.id'], ),
    sa.ForeignKeyConstraint(['recolector_id'], ['recolectores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('procesos_limpieza',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lote_materia_prima_id', sa.Integer(), nullable=False),
    sa.Column('responsable_id', sa.Uuid(), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=True),
    sa.Column('hora_final', sa.Time(), nullable=True),
    sa.Column('total_kg_ingreso', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('total_kg_salida', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('numero_procesos', sa.Integer(), nullable=True),
    sa.Column('es_organico', sa.Boolean(), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('firma_responsable_planilla', sa.Boolean(), nullable=False),
    sa.Column('vobo_planta', sa.Boolean(), nullable=False),
    sa.Column('vobo_control_calidad', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['lote_materia_prima_id'], ['lotes_materia_prima.id'], ),
    sa.ForeignKeyConstraint(['responsable_id'], ['usuarios_sistema.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lote_materia_prima_id', name='uq_limpieza_lote')
    )
    op.create_table('items_recepcion',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lote_materia_prima_id', sa.Integer(), nullable=False),
    sa.Column('recolector_id', sa.Integer(), nullable=False),
    sa.Column('entrega_recolector_id', sa.Integer(), nullable=True),
    sa.Column('autorizacion_recolector_id', sa.Integer(), nullable=True),
    sa.Column('zona_autorizacion', sa.String(length=100), nullable=True),
    sa.Column('tipo_asai', sa.String(length=20), nullable=True),
    sa.Column('numero_compra', sa.Integer(), nullable=True),
    sa.Column('peso_kg', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('precio_bs_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('precio_total_bs', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('firma_entrega', sa.Boolean(), nullable=False),
    sa.Column('firma_pago', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['autorizacion_recolector_id'], ['autorizaciones_recolector.id'], ),
    sa.ForeignKeyConstraint(['entrega_recolector_id'], ['entregas_recolector.id'], ),
    sa.ForeignKeyConstraint(['lote_materia_prima_id'], ['lotes_materia_prima.id'], ),
    sa.ForeignKeyConstraint(['recolector_id'], ['recolectores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('procesos_ablandamiento',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lote_materia_prima_id', sa.Integer(), nullable=False),
    sa.Column('proceso_limpieza_id', sa.Integer(), nullable=False),
    sa.Column('responsable_id', sa.Uuid(), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=True),
    sa.Column('hora_final', sa.Time(), nullable=True),
    sa.Column('total_kg_ingreso', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('total_kg_salida', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('numero_procesos', sa.Integer(), nullable=True),
    sa.Column('es_organico', sa.Boolean(), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('firma_responsable_planilla', sa.Boolean(), nullable=False),
    sa.Column('vobo_planta', sa.Boolean(), nullable=False),
    sa.Column('vobo_control_calidad', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['lote_materia_prima_id'], ['lotes_materia_prima.id'], ),
    sa.ForeignKeyConstraint(['proceso_limpieza_id'], ['procesos_limpieza.id'], ),
    sa.ForeignKeyConstraint(['responsable_id'], ['usuarios_sistema.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lote_materia_prima_id', name='uq_ablandamiento_lote')
    )
    op.create_table('subprocesos_limpieza',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('proceso_limpieza_id', sa.Integer(), nullable=False),
    sa.Column('numero_proceso', sa.Integer(), nullable=False),
    sa.Column('hora_inicio_seco', sa.Time(), nullable=True),
    sa.Column('hora_final_seco', sa.Time(), nullable=True),
    sa.Column('residuos_kg', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('tipo_recipiente_inmersion', sa.String(length=50), nullable=True),
    sa.Column('hora_inicio_lavado', sa.Time(), nullable=True),
    sa.Column('hora_final_lavado', sa.Time(), nullable=True),
    sa.ForeignKeyConstraint(['proceso_limpieza_id'], ['procesos_limpieza.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('procesos_elaboracion_pulpa',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lote_materia_prima_id', sa.Integer(), nullable=False),
    sa.Column('proceso_ablandamiento_id', sa.Integer(), nullable=False),
    sa.Column('responsable_id', sa.Uuid(), nullable=False),
    sa.Column('es_organico', sa.Boolean(), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('firma_responsable_planilla', sa.Boolean(), nullable=False),
    sa.Column('vobo_planta', sa.Boolean(), nullable=False),
    sa.Column('vobo_control_calidad', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['lote_materia_prima_id'], ['lotes_materia_prima.id'], ),
    sa.ForeignKeyConstraint(['proceso_ablandamiento_id'], ['procesos_ablandamiento.id'], ),
    sa.ForeignKeyConstraint(['responsable_id'], ['usuarios_sistema.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lote_materia_prima_id', name='uq_elaboracion_lote')
    )
    op.create_table('subprocesos_ablandamiento',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('proceso_id', sa.Integer(), nullable=False),
    sa.Column('numero_proceso', sa.Integer(), nullable=False),
    sa.Column('tipo_recipiente_ablandamiento', sa.String(length=50), nullable=True),
    sa.Column('litros_agua_ablandamiento', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('tipo_recipiente_enfriado', sa.String(length=50), nullable=True),
    sa.Column('litros_agua_enfriado_t1000', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('litros_agua_enfriado_canastas', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('hora_inicio', sa.Time(), nullable=True),
    sa.Column('hora_final', sa.Time(), nullable=True),
    sa.Column('temp_inicio', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('temp_intermedia', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('temp_final', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('diferencia_temp', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['proceso_id'], ['procesos_ablandamiento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lotes_producto_terminado',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('numero_lote', sa.String(length=50), nullable=False),
    sa.Column('proceso_elaboracion_id', sa.Integer(), nullable=False),
    sa.Column('lote_materia_prima_id', sa.Integer(), nullable=False),
    sa.Column('fecha_proceso', sa.Date(), nullable=True),
    sa.Column('hora_inicio', sa.Time(), nullable=True),
    sa.Column('hora_final', sa.Time(), nullable=True),
    sa.Column('tipo_pulpa', sa.String(length=20), nullable=False),
    sa.Column('unidad_envase', sa.String(length=20), nullable=True),
    sa.Column('total_kg_fruto', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('total_kg_pulpa', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('rendimiento_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('porcentaje_solidos', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('grados_brix', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('ph', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('es_organico', sa.Boolean(), nullable=False),
    sa.Column('total_kg', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('stock_actual_kg', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['lote_materia_prima_id'], ['lotes_materia_prima.id'], ),
    sa.ForeignKeyConstraint(['proceso_elaboracion_id'], ['procesos_elaboracion_pulpa.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_lote')
    )
    op.create_table('inventario_camara_frio',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('responsable_id', sa.Uuid(), nullable=False),
    sa.Column('lote_producto_terminado_id', sa.Integer(), nullable=False),
    sa.Column('tipo_pulpa', sa.String(length=20), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('tipo_envase', sa.String(length=50), nullable=True),
    sa.Column('unidad', sa.String(length=20), nullable=True),
    sa.Column('cantidad', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('fecha_ingreso', sa.Date(), nullable=True),
    sa.Column('fecha_salida', sa.Date(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('firma_responsable_planilla', sa.Boolean(), nullable=False),
    sa.Column('vobo_planta', sa.Boolean(), nullable=False),
    sa.Column('vobo_control_calidad', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['lote_producto_terminado_id'], ['lotes_producto_terminado.id'], ),
    sa.ForeignKeyConstraint(['responsable_id'], ['usuarios_sistema.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('items_choque_termico',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sesion_id', sa.Integer(), nullable=False),
    sa.Column('lote_producto_terminado_id', sa.Integer(), nullable=False),
    sa.Column('numero_freezer', sa.Integer(), nullable=True),
    sa.Column('tipo_pulpa', sa.String(length=20), nullable=True),
    sa.Column('tipo_envase', sa.String(length=50), nullable=True),
    sa.Column('unidad', sa.String(length=20), nullable=True),
    sa.Column('cantidad', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('fecha_ingreso', sa.Date(), nullable=True),
    sa.Column('fecha_salida', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['lote_producto_terminado_id'], ['lotes_producto_terminado.id'], ),
    sa.ForeignKeyConstraint(['sesion_id'], ['sesiones_choque_termico.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('items_despacho',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('despacho_id', sa.Integer(), nullable=False),
    sa.Column('lote_producto_terminado_id', sa.Integer(), nullable=False),
    sa.Column('fecha_despacho', sa.Date(), nullable=True),
    sa.Column('numero_lote', sa.String(length=50), nullable=True),
    sa.Column('peso_kg', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('numero_cajas', sa.Integer(), nullable=True),
    sa.Column('subtotal_bs', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['despacho_id'], ['despachos.id'], ),
    sa.ForeignKeyConstraint(['lote_producto_terminado_id'], ['lotes_producto_terminado.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matrices_procesos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lote_producto_terminado_id', sa.Integer(), nullable=True),
    sa.Column('responsable_id', sa.Uuid(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['lote_producto_terminado_id'], ['lotes_producto_terminado.id'], ),
    sa.ForeignKeyConstraint(['responsable_id'], ['usuarios_sistema.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lote_producto_terminado_id', name='uq_matriz_lpt')
    )
    op.create_table('items_matriz_procesos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('matriz_id', sa.Integer(), nullable=False),
    sa.Column('proceso', sa.String(length=50), nullable=False),
    sa.Column('responsable_nombre', sa.String(length=200), nullable=True),
    sa.Column('tareas_principales', sa.Text(), nullable=True),
    sa.Column('herramientas_equipos', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['matriz_id'], ['matrices_procesos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('items_matriz_procesos')
    op.drop_table('matrices_procesos')
    op.drop_table('items_despacho')
    op.drop_table('items_choque_termico')
    op.drop_table('inventario_camara_frio')
    op.drop_table('lotes_producto_terminado')
    op.drop_table('subprocesos_ablandamiento')
    op.drop_table('procesos_elaboracion_pulpa')
    op.drop_table('subprocesos_limpieza')
    op.drop_table('procesos_ablandamiento')
    op.drop_table('items_recepcion')
    op.drop_table('procesos_limpieza')
    op.drop_table('entregas_recolector')
    op.drop_table('sesiones_choque_termico')
    op.drop_table('lotes_materia_prima')
    op.drop_table('despachos')
    # ### end Alembic commands ###
