"""parcela_move_fk_to_recolector

Revision ID: 2ab7a362573c
Revises: cffceba8b4c8
Create Date: 2026-08-16 11:48:42.303952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ab7a362573c'
down_revision: Union[str, Sequence[str], None] = 'cffceba8b4c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parcelas', sa.Column('recolector_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('parcelas_autorizacion_recolector_id_fkey'), 'parcelas', type_='foreignkey')
    op.create_foreign_key(None, 'parcelas', 'recolectores', ['recolector_id'], ['id'])
    op.drop_column('parcelas', 'autorizacion_recolector_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parcelas', sa.Column('autorizacion_recolector_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'parcelas', type_='foreignkey')
    op.create_foreign_key(op.f('parcelas_autorizacion_recolector_id_fkey'), 'parcelas', 'autorizaciones_recolector', ['autorizacion_recolector_id'], ['id'])
    op.drop_column('parcelas', 'recolector_id')
    # ### end Alembic commands ###
