"""remove_lote_id_from_entrega_recolector

Revision ID: a36ca27d8c42
Revises: 2ab7a362573c
Create Date: 2026-08-16 12:21:34.540560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a36ca27d8c42'
down_revision: Union[str, Sequence[str], None] = '2ab7a362573c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('entregas_recolector_lote_materia_prima_id_fkey'), 'entregas_recolector', type_='foreignkey')
    op.drop_column('entregas_recolector', 'lote_materia_prima_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entregas_recolector', sa.Column('lote_materia_prima_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('entregas_recolector_lote_materia_prima_id_fkey'), 'entregas_recolector', 'lotes_materia_prima', ['lote_materia_prima_id'], ['id'])
    # ### end Alembic commands ###
