"""add_recolectores_autorizaciones_zafra

Revision ID: acb6d03f7b72
Revises: ff96652849ab
Create Date: 2026-08-16 07:07:38.529517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acb6d03f7b72'
down_revision: Union[str, Sequence[str], None] = 'ff96652849ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('autorizaciones_zafra',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('comunidad_id', sa.Integer(), nullable=False),
    sa.Column('creado_por', sa.Uuid(), nullable=False),
    sa.Column('codigo_documento', sa.String(length=100), nullable=True),
    sa.Column('solicitante', sa.String(length=200), nullable=False),
    sa.Column('ci_solicitante', sa.String(length=20), nullable=True),
    sa.Column('expediente', sa.String(length=100), nullable=True),
    sa.Column('cosecha', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio_recoleccion', sa.Date(), nullable=True),
    sa.Column('fecha_fin_recoleccion', sa.Date(), nullable=True),
    sa.Column('n_dias_recoleccion', sa.Integer(), nullable=True),
    sa.Column('superficie_km2', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('zona_autorizacion', sa.String(length=200), nullable=True),
    sa.Column('sello_sernap', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['comunidad_id'], ['comunidades.id_comunidad'], ),
    sa.ForeignKeyConstraint(['creado_por'], ['usuarios_sistema.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recolectores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.Column('comunidad_id', sa.Integer(), nullable=False),
    sa.Column('creado_por', sa.Uuid(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('nombre_completo', sa.String(length=200), nullable=False),
    sa.Column('ci', sa.String(length=20), nullable=False),
    sa.Column('documento_tenencia', sa.Text(), nullable=True),
    sa.Column('codigo_tc', sa.Text(), nullable=True),
    sa.Column('especie', sa.String(length=100), nullable=True),
    sa.Column('fecha_registro', sa.Date(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['comunidad_id'], ['comunidades.id_comunidad'], ),
    sa.ForeignKeyConstraint(['creado_por'], ['usuarios_sistema.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios_sistema.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_table('autorizaciones_recolector',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('autorizacion_zafra_id', sa.Integer(), nullable=False),
    sa.Column('recolector_id', sa.Integer(), nullable=False),
    sa.Column('especie', sa.String(length=100), nullable=True),
    sa.Column('poligono_gps', sa.JSON(), nullable=True),
    sa.Column('superficie_ha', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('produccion_estimada_kg', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('estado_recoleccion', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['autorizacion_zafra_id'], ['autorizaciones_zafra.id'], ),
    sa.ForeignKeyConstraint(['recolector_id'], ['recolectores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('autorizacion_zafra_id', 'recolector_id', name='uq_autorizacion_recolector')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('autorizaciones_recolector')
    op.drop_table('recolectores')
    op.drop_table('autorizaciones_zafra')
    # ### end Alembic commands ###
