"""add_parcela_table

Revision ID: cffceba8b4c8
Revises: 635a0fda694c
Create Date: 2026-08-16 11:40:22.343410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cffceba8b4c8'
down_revision: Union[str, Sequence[str], None] = '635a0fda694c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parcelas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('autorizacion_recolector_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=True),
    sa.Column('poligono_gps', sa.JSON(), nullable=True),
    sa.Column('superficie_ha', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('especie', sa.String(length=100), nullable=True),
    sa.Column('produccion_estimada_kg', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['autorizacion_recolector_id'], ['autorizaciones_recolector.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('autorizaciones_recolector', 'superficie_ha')
    op.drop_column('autorizaciones_recolector', 'especie')
    op.drop_column('autorizaciones_recolector', 'produccion_estimada_kg')
    op.drop_column('autorizaciones_recolector', 'poligono_gps')
    op.add_column('entregas_recolector', sa.Column('parcela_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'entregas_recolector', 'parcelas', ['parcela_id'], ['id'])
    op.add_column('items_recepcion', sa.Column('parcela_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'items_recepcion', 'parcelas', ['parcela_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'items_recepcion', type_='foreignkey')
    op.drop_column('items_recepcion', 'parcela_id')
    op.drop_constraint(None, 'entregas_recolector', type_='foreignkey')
    op.drop_column('entregas_recolector', 'parcela_id')
    op.add_column('autorizaciones_recolector', sa.Column('poligono_gps', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('autorizaciones_recolector', sa.Column('produccion_estimada_kg', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('autorizaciones_recolector', sa.Column('especie', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('autorizaciones_recolector', sa.Column('superficie_ha', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=True))
    op.drop_table('parcelas')
    # ### end Alembic commands ###
